[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Documents"
desc = "go to whatsapp Media/Documents"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd sftp://gd"
desc = "go to Google Drive (via rclone serve sftp)"

