[manager]
ratio = [1, 2, 6]

[preview]
max_width = 10000
max_height = 20000
image_delay = 0

[opener]
image = [
    { run = "magick %f", block = false }
]

[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*/"
run   = "git"
group = "git"
